### ISSUE TITLE
White screen after resume from background

### ISSUE THREAD

**Issue by ElaineKong** [MOLPay/rms-mobile-xdk-ios#7]
I'm using the latest version, which is 3.27.0 in iOS Swift 5.

Every time I resume the app from background (when I was in the MOLPay payment page from the SDK), the screen becomes blank. I found there is a UIWindow added on top of the MOLPay payment page. It blocked users from proceeding to do the payment, especially when users want to check their SMS for bank TAC codes.

Picture below shows UI hierarchy which the MOLPay payment page is underneath the white background UIWindow after resume from background.

![Simulator Screen Shot - iPhone Xʀ - 2019-10-08 at 18 06 20](https://user-images.githubusercontent.com/13358323/66410148-388d0900-ea24-11e9-8c3d-16c6e52c334d.png)

Any advices?

**Comment by clewlb** [comment]
Thanks for reaching out, the XDK doesn't add the UIWindow nor it has anything to do with it. However, we suggest you try out our example project and see if similar effects appeared on you, and if it does, please let us know, otherwise, you can refer to our example project codes for the proper integration guides.

**Comment by ElaineKong** [comment]
I've tested in the example project. The example project is currently using storyboard. But if i changed it, by adding these code

`
window = UIWindow(frame: UIScreen.main.bounds)
window?.makeKeyAndVisible()
        
let viewController: ViewController = ViewController()
let navigationController = UINavigationController(rootViewController: viewController)
window?.rootViewController = navigationController
`

in AppDelegate didFinishLaunchingWithOptions. Turn the app into background, resume, the MOLPay payment page will covered by the white background UIWindow too.

Please investigate. Thanks

**Comment by clewlb** [comment]
We recommend you use the storyboard as we suggested in the example project.
