### ISSUE TITLE
A error for iOS

### ISSUE THREAD

**Issue by aas454450123** [MOLPay/rms-mobile-xdk-ios#8]
After following the setup instructions I got a error for iOS platforms on runtime.
{"Error":"Communication Error, please check internet connection, username, or password"}

**Comment by clewlb** [comment]
@aas454450123 The XDK requires valid merchant credentials to perform end-to-end test, and you can request one from support-sa@razer.com. If you just wanted to try out the offline simulation without the credentials, you can turn on the sandbox mode, @"mp_sandbox_mode": [NSNumber numberWithBool:YES], and this will allow you to test in the local simulated environment.

**Comment by aas454450123** [comment]
Thank you
